### ISSUE TITLE
Works in vert.x 3.1.0, Vertx.clusteredVertx never returns in 3.2.0

### ISSUE THREAD

**Issue by cinterloper** [atomix/atomix-vertx#1]
You may already know this, but i have tested against V 3.1 and 3.2

3.1 appears to work

3.2 never returns : 
    Vertx.clusteredVertx(options, ar -> {
                log.info("We got a .clusteredVertx result "+ar); //this never happens in 3.2
                result.set(ar);
                latch.countDown();
            });

**Comment by cinterloper** [comment]
no longer valid

**Comment by kuujo** [comment]
Oh thanks, I missed this somehow. We've been fixing some issues in Copycat
and it seems to be having much better now.

**Comment by cinterloper** [comment]
I really want to use this,
- is there an upcoming checkpoint i could wait for? 
- a set of known issues that need fixing?
- sharp corners to watch out for?

**Comment by kuujo** [comment]
Glad to hear that :-)

In general, Copycat (the Raft implementation) is feature complete and is believed to be stable. The full 1.0 release will be pushed some time this week. Atomix is thought to be slightly behind Copycat but is also thought to be stable. The final known issues in Copycat were fixed this weekend, and the result was consistently passing tests in this project.

The test suite comes from Vert.x itself, so passing tests lend themselves to the idea that the project is stable. But one would assume there are still some issues with running it in a production environment. For example, I see it's using `getResourceAsStream` to load properties files, and that should be changed. But aside from those types of minor details, no significant issues are known to remain.

I'll be releasing Copycat 1.0, another Atomix RC with updated Copycat dependencies, and this project at various points this week. That feels like a good checkpoint.
